name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build and Test (${{ matrix.goos }} ${{ matrix.arch }})
    runs-on: ${{ matrix.runs_on }}
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            runs_on: ubuntu-latest
            goos: linux
          - arch: arm64
            runs_on: ubuntu-24.04-arm
            goos: linux
          - arch: amd64
            runs_on: windows-2022
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 #v6.2.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Set environment variables (Linux)
        if: ${{ matrix.goos == 'linux' }}
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "GOOS=${{ matrix.goos }}" >> "$GITHUB_ENV"

      - name: Set environment variables (Windows)
        if: ${{ matrix.goos == 'windows' }}
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> "$env:GITHUB_ENV"
          echo "GOOS=${{ matrix.goos }}" >> "$env:GITHUB_ENV"

      - name: Verify
        run: make verify

      - name: Build
        run: make build

      - name: Test
        run: make test
